version: '3.8'

services:
  db:
    env_file:
      - .env
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "8000:6000"
    depends_on:
      - db
    command: ["wait-for-it", "db:5432", "--", "/docker-billing"]
volumes:
  postgres-db:
